SplashActivity 작성
sbs0516/DontCallInDrunk pull request #2
Opened 2022-02-21 10:33 UTC by sbs05166

SplashActivity 작성
  - ViewModel 에서 postDelayed 적용
  - check: MutableLiveData<Boolean> 값을 사용해서 delay 여부 확인

2022-02-21 12:53 UTC, UnsignedUSB requested changes

2022-02-21 12:53 UTC, UnsignedUSB commented on app/src/main/java/com/example/dontcallindrunk/splash/SplashActivity.kt
> +    lateinit var splashViewDataBinding: ActivitySplashBinding
by lazy{} 라고 있어.
한번 찾아보고 이 Binding 구문을 어떻게 하면 by lazy{}를 이용해서 쓸 수 있을지 한번 찾아봐.

2022-02-21 12:53 UTC, UnsignedUSB commented on app/src/main/java/com/example/dontcallindrunk/splash/SplashActivity.kt
> +        splashViewDataBinding.lifecycleOwner = this
splashViewDataBinding은 그래도 코드를 붙여두는게 추후 읽기도, 보기도 좋겠지?

2022-02-21 12:53 UTC, UnsignedUSB commented on app/src/main/java/com/example/dontcallindrunk/splash/SplashActivity.kt
> +        })
의도는 좋았는데, 이렇게 하면 Delay라는 것을 ViewModel의 로직으로 처리 된 것이 아니라 SplashActivity에서 실행시킨 꼴이 되지.
그리고 LiveData를 이용한 시도는 좋았는데, LiveData는 이런 목적을 갖지는 않아.

너가 참고하면 좋을만한 것은
Button View에 OnClickListener를 붙여두고, 클릭이 발생하면 OnClickListener로 그 클릭이 넘어오는 구조야.
이걸 Listener 혹은 Callback 구조라고 하지. Callback. 말 그대로 "되 불러주는 것" 
Callback을 등록해두고, 상황이 발생했을 때, 해당 Callback으로 받게 된 이벤트를 수행하는 것.
Android에서는 "가장" 기본적이고 그렇기에 반드시 알아야만 하는 것이야.
아래 링크를 보고 이해를 한 다음 그런 Listener 구조로 변경해봐
https://velog.io/@dev_2dong/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-Callback-%EA%B5%AC%ED%98%84%EC%97%90-%EB%8C%80%ED%95%9C-%EC%9D%B4%ED%95%B4

2022-02-21 12:53 UTC, UnsignedUSB commented on app/src/main/java/com/example/dontcallindrunk/splash/SplashActivity.kt
> +        finish()
약간 코드가 아깝지
굳이 이럴 필요가 없는거야
```kotlin
startActivity( Intent(this, MainActivity::class.java) )
finish()
```
요러면 깔끔하지.

2022-02-21 12:53 UTC, UnsignedUSB commented on app/src/main/java/com/example/dontcallindrunk/splash/SplashViewModel.kt
> +        }, 3000)
스플래시를 한다고 했을 때, 대기한 다음 넘기는 방법은 여러가지가 있겠지.
그 중 Handler가 진짜 제일 기본인데, 이 기본기를 확실히 다져두고 가는게 중요하다고 생각해. 
나는 면접 볼 때 항상 물어보는 것 중 하나야.
- Handler는 뭐하는 녀석이고, 어떤 역할을 하며, 이것과 관련이 있는 컴포넌트들과 함께 Handler의 동작 구조를 설명하라
- Handler를 보면 sendMessage가 있고, obtainMessage가 있는데 이 둘의 차이는?
https://brunch.co.kr/@mystoryg/84
위 링크를 통해 기본적인 것을 공부해봐.
실 구현보다 더 중요한 거고, 당연히 Study Wiki쪽에 정리해둬야겠지?

Handler를 더 파보려면 몇 가지 샘플 코드들을 작성해보면서 이해하는게 좋아.
더 나아가서 Handler의 실제 구현코드를 따라가면서 이해하고 그걸 정리하는 것도 한다면 더 좋은데, 
이건 한번 공부 해보고 보자. 

```kotlin
        val handler = Handler()
        handler.postDelayed( {
            check.value = true
        }, 3000)
```
그리고 공부를 마친다음. 현재 위 코드가 어떤 문제가 발생할 수 있는지 한번 생각해봐. 위 코드는 큰 문제를 가지고 있어.

이 내용은 이번주 토요일까지 정리해서 이야기 해보자.

2022-02-21 12:53 UTC, UnsignedUSB commented on app/src/main/res/layout/activity_splash.xml
> +    tools:context=".splash.SplashActivity">
앞으로 구현하면서 가능하면 LinearLayout보다 ConstraintLayout을 사용하자.
진짜 간단한 UI들. 반드시 일렬로 나열되어야만 하는 부분은 LinearLayout를 써야 하지만
그렇지 않은 부분은 ConstraintLayout으로만 구성하도록.

2022-02-21 12:53 UTC, UnsignedUSB commented on app/src/main/java/com/example/dontcallindrunk/splash/Event.kt
> +}
얘는 쓰는 곳이 없는 것 같은데?

2022-02-23 16:06 UTC, UnsignedUSB commented on app/src/main/java/com/example/dontcallindrunk/splash/SplashActivity.kt
> +    }
👍

2022-02-23 16:06 UTC, UnsignedUSB commented on app/src/main/java/com/example/dontcallindrunk/splash/SplashActivity.kt
> +    }
by lazy 코드들은 {}로 감싸져 있다더라도, 변수의 선언이라, 가능하면 한줄로 표현해주는게 일반적이야.
물론 맨 위에 apply로 넣어주는 경우는 좀 다르긴 하지만.

2022-02-23 16:06 UTC, UnsignedUSB commented on app/src/main/java/com/example/dontcallindrunk/splash/SplashActivity.kt
> +        splashViewDatabinding.delayBtn.performClick()
요건 왜? 강제로 Click을 발생시키는 코드는 별로 좋지 않은데.

2022-02-23 16:06 UTC, UnsignedUSB commented on app/src/main/java/com/example/dontcallindrunk/splash/SplashActivity.kt
> +            override fun onDelay() {
개발자의 난제. 네이밍인데.
setListener는 너무 범용적인 이름이야.
이 경우는 Listner가 1개뿐이라 당장은 문제가 되지 않을 수 있지만, setOnDelayListener()로 해두는 것이 좀 더 코드를 읽기에 좋겠지.

그리고 onDelay() 부분도 이름의 의미가 애매하지.
onDone() 같은것이 좀 더 좋긴 할 것 같아.

2022-02-24 10:48 UTC, sbs05166 commented on app/src/main/java/com/example/dontcallindrunk/splash/SplashViewModel.kt
> +        }, 3000)
Handler 코드 수정
  - Worker Thread 와 Main Thread 를 구분 / 비동기 작업이 실행되어야 하는데 Worker Thread 안에서 Handler 객체를 생성하고 바로 post() 를 넣어서 문제가 발생할 수 있다 라고 생각함
  - Handler 를 ViewModel 안에서 생성하고, 이것을 이용하여 post() 함

2022-03-13 12:38 UTC, UnsignedUSB approved these changes
👍

2022-03-13 12:38 UTC, merged